homeassistant:
  name: Vas & Squrriels Castle
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include Customize.yaml
  packages: !include_dir_named packages

####Zone files
zone: !include zones.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
  # base_url: !secret http_base_url
   use_x_forwarded_for: True
   trusted_networks:
     - 127.0.0.1
     - 192.168.1.0/24
   ip_ban_enabled: True
   login_attempts_threshold: 5

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Track the sun
sun:

# Sensors
sensor: !include Sensors.yaml

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

group: !include tabs.yaml

mqtt:
  broker: 192.168.1.153
  port: 1883
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

intent_script: !include intent_scripts.yaml
alexa:

script: !include scripts.yaml

automation old: !include automations old.yaml

light:
  platform: hue
  host: 192.168.1.185
  allow_unreachable: True

scene: !include Scenes.yaml

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

rest_command: !include restcommands.yaml

config:

wink:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

weblink:
  entities:
    - name: Fish Tank HA
      url: !secret fish_tank_url
      icon: mdi:fish
    - name: Dashboard
      url: http://192.168.1.153:5050/vas
      icon: mdi:view-dashboard
    - name: Plex
      url: https://app.plex.tv/desktop
      icon: mdi:plex

#discovery:
panel_iframe:
  home_assistant:
    title: 'Wind'
    icon: mdi:weather-windy
    url: 'https://embed.windy.com/embed2.html?lat=30.422&lon=-90.196&zoom=5&level=surface&overlay=wind&menu=&message=&marker=&forecast=12&calendar=now&location=coordinates&type=map&actualGrid=&metricWind=kt&metricTemp=%C2%B0C'

  home_assistant_fishtank:
    title: 'HA Fishtank'
    icon: mdi:home-assistant
    url: 'https://vasiley.dns1.us:444'

  plex_web_server:
    title: 'Plex'
    icon: mdi:plex
    url: https://app.plex.tv/desktop
