homeassistant:
  customize:
    script.herbearly_on:
      friendly_name: Morning

#########################################################################################
#                                                                                   #####
#                   Early Morning Mode                                              #####
#                                                                                   #####
#########################################################################################
script:
  herbearly_on:
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_early_morning
      - service: script.turn_on
        entity_id: script.led_white    
      - service: switch.turn_on
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:01'
      - service: tts.google_say
        data_template:
          entity_id: media_player.ha_speaker
          message: 'Good Morning Herb how are you this morning The weather for today is{{states.sensor.dark_sky_daily_summary.state}}'
      - service: script.blinds_halfway
      - delay: '00:00:10'
      - service: input_select.select_option
        data:
          entity_id: input_select.harmony
          option: 'Classic Music'
      - delay: '00:00:04'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.stereo
          volume_level: '.60'
      - service: light.turn_on
        data:
          entity_id: light.herbs_lamp
          color_temp: 200
          brightness: 175
      - service: rest_command.no_motion
      - service: rest_command.no_motion

# rest_command sets profile of blue iris software
