homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'iboot_hack'

    switch.ibootone:
      persistent: true
    switch.dawns_scent:
      haaska_name: Dawns Scent
      friendly_name: Dawns Scent
      icon: mdi:flower
      persistent: true

group:
  iboot_card:
   name: Iboots
   entities:
     - switch.dawns_scent


switch:

        #command_example: 'curl --data "A=POWERON" --anyauth --user <username>:<pass> <ip>/P0.HTML'
  - platform: command_line
    switches:
      dawns_scent:
        command_on: !secret iboot2_on
        command_off: !secret iboot2_off

automation:
  - alias: dawns_scent_on
    trigger:
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Home'
    action:
      - service: switch.turn_on
        entity_id: switch.dawns_scent
      - service: switch.turn_on
        entity_id: switch.dawns_scent

  - alias: dawns_scent_off
    trigger:
      - platform: state
        entity_id: sensor.house_mode_state
        to: 'Evening Time'
    action:
      - service: switch.turn_off
        entity_id: switch.dawns_scent
      - service: switch.turn_off
        entity_id: switch.dawns_scent
