homeassistant:
  customize:

    package.node_anchors:
      customize: &customize
        package: 'Kitchen Mains'

    binary_sensor.kitchen_motion:
      friendly_name: Kitchen Motion
      device_class: motion
    sensor.kitchen_battery_motion:
      friendly_name: Kitchen Motion Battery
    sensor.motion_sensor_kitchen_lux:
      friendly_name: Kitchen Light Level
    sensor.kitchen_table_dimmer_battery:
      icon: mdi:battery
    sensor.kitchen_table_dimmer_last_update:
      icon: mdi:clock
    sensor.kitchen_table_dimmer_state:
      icon: mdi:remote

binary_sensor:
  - platform: rest
    resource: !secret MS_rest_6
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: kitchen_motion

sensor:
  - platform: rest
    resource: !secret MS_rest_5
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Kitchen Temperature'
  - platform: rest
    resource: !secret MS_rest_5
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Kitchen Battery'
  - platform: rest
    resource: !secret MS_rest_7
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    scan_interval: 5
    name: 'Motion Sensor Kitchen Lux'
  - platform: rest
    resource: !secret dimmer_rest_9
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Kitchen Table Dimmer Battery'
  - platform: rest
    resource: !secret dimmer_rest_9
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 1
    name: 'Kitchen Table Dimmer State'
  - platform: template
    sensors:
      kitchen_table_dimmer_state:
        friendly_name: 'Kitchen Table Dimmer Last Button Push'
        value_template: >-
                      {% if states('sensor.kitchen_table_dimmer_state_2')[0] == "1" %}
                        On
                      {% elif states('sensor.kitchen_table_dimmer_state_2')[0] == "4" %}
                        Off
                      {% else %}
                        None
                      {% endif %}
  - platform: rest
    resource: !secret dimmer_rest_9
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'kitchen table dimmer last update'
  - platform: template
    sensors:
      kitchen_table_dimmer_last_update:
        friendly_name: 'Kitchen Table Last Used'
        value_template: >-
          {{as_timestamp(strptime(states('sensor.kitchen_table_dimmer_last_update_2')[:19], "%Y-%m-%dT%X"))|timestamp_custom("%a, %B %d")}}

automation:
  - alias: Motion Kitichen Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_home
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.motion_sensor_kitchen_lux
        below: '14000'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen
          color_temp: 154
          brightness: 255

  - alias: Motion Kitchen Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'off'
        for:
          minutes: 3
    action:
      - service: light.turn_off
        data:
          entity_id: light.kitchen
          transition: 15

  - alias: Motion Kitchen not home mode yellow
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
    condition:
      condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.boolean_early_morning
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_movie_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_evening_time
        state: 'on'
      - condition: state
        entity_id: input_boolean.boolean_sleep
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.kitchen
          color_temp: 426
          brightness: 100
