homeassistant:
  customize:
    sensor.fish_tank_cpu_use:
      friendly_name: Fish Tank Cpu
      icon: mdi:desktop-tower
    sensor.fish_tank_disk_use:
      friendly_name: Fish Tank Disk
      icon:  mdi:harddisk
    sensor.fish_tank_ram_free:
      friendly_name: Ram
      icon: mdi:memory
    sensor.fish_tank_ha_version:
      friendly_name: Fish Tank Ha
      icon: mdi:home-assistant
    sensor.fish_tank_ha_uptime:
      friendly_name: Fish Tank Ha Uptime
      icon: mdi:home-assistant
    sensor.ha_temperature:
      friendly_name: Ha Temperature
      icon: mdi:temperature-fahrenheit
      hasska_hidden: true
    sensor.ha_humidity:
      friendly_name: Ha Humidity
      icon: mdi:water-percent
      hasska_hidden: true
    sensor.small_tank_water_temperature:
      friendly_name: Water Temperature
      icon: mdi:temperature-fahrenheit
      hasska_hidden: true
    sensor.small_tank_heater:
      icon: mdi:thermometer-lines
      friendly_name: Heater
      hasska_hidden: true
    sensor.small_tank_white_lights:
      icon: mdi:led-strip
      friendly_name: Small Tank White Lights
      hasska_hidden: true
group:
  Fish_tank_server_info:
   name: Server Info
   entities:
     - sensor.fish_tank_cpu_use
     - sensor.fish_tank_disk_use
     - sensor.fish_tank_ram_free
     - sensor.fish_tank_ha_version
     - sensor.fish_tank_ha_uptime

  Fish_tank_server_ext_info:
     name: Server Exterior Info
     entities:
       - sensor.ha_temperature
       - sensor.ha_humidity

  water_sensors:
   name: Small Tank Sensors
   entities:
     - sensor.small_tank_water_temperature

  controls:
   name: Controls
   entities:
    - sensor.small_tank_heater
    - sensor.small_tank_white_lights
    - sensor.small_tank_lighting_mode
    - sensor.small_tank_weather_mode
sensor:
  - platform: rest
    resource: !secret sensor_fish_tank_url
    value_template: '{{ value_json.state }}'
    name: Fish Tank Cpu Use
    unit_of_measurement: "%"

  - platform: rest
    resource: !secret fish_tank_disk_use
    value_template: '{{ value_json.state }}'
    name: Fish Tank Disk Use
    unit_of_measurement: "%"

  - platform: rest
    resource: !secret fish_tank_ram_free
    value_template: '{{ value_json.state }}'
    name: Fish Tank Ram Free
    unit_of_measurement: "Mb"

  - platform: rest
    resource: !secret fish_tank_ha_version
    value_template: '{{ value_json.state }}'
    name: Fish Tank Ha Version

  - platform: rest
    resource: !secret fish_tank_ha_uptime
    value_template: '{{ value_json.state }}'
    name: Fish Tank Ha Uptime

  - platform: rest
    resource: !secret ha_temperature
    value_template: '{{ value_json.state }}'
    name: Ha Temperature
    unit_of_measurement: '°F'

  - platform: rest
    resource: !secret ha_humidity
    value_template: '{{ value_json.state }}'
    name: Ha Humidity

  - platform: rest
    resource: !secret small_tank_water_temperature
    value_template: '{{ value_json.state }}'
    name: Small Tank Water Temperature
    unit_of_measurement: '°F'

  - platform: rest
    resource: !secret small_relay_one
    value_template: '{{ value_json.state }}'
    name: Relay One

  - platform: rest
    resource: !secret small_relay_three
    value_template: '{{ value_json.state }}'
    name: Small Tank White Lights

  - platform: rest
    resource: !secret small_relay_two
    value_template: '{{ value_json.state }}'
    name: Relay Two

  - platform: rest
    resource: !secret small_relay_four
    value_template: '{{ value_json.state }}'
    name: Small Tank Heater

  - platform: rest
    resource: !secret fish_tank_sensor_light_mode
    value_template: '{{ value_json.state }}'
    name: Small Tank Lighting Mode

  - platform: rest
    resource: !secret fish_tank_sensor_light_weather
    value_template: '{{ value_json.state}}'
    name: Small Tank Weather Mode
